services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    extra_hosts:
      - "identity.todoapp.local:127.0.0.1"
    depends_on:
      - db
    environment:
      - APP_ENV=development
    command: bash -c "./update_hosts.sh && php artisan key:generate && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network: