@startuml
title グループ
left to right direction
actor ユーザー
actor システム
actor 招待者
rectangle {
   ユーザー --> (グループ一覧を閲覧する)
   ユーザー --> (グループに所属しているユーザーを閲覧する)
   ユーザー --> (グループ名を入力して\nグループを新規作成する)
   ユーザー --> (グループにユーザーを招待する)
   (招待されたユーザー宛てに招待メールを送信する) <-- システム
}

rectangle {
    招待者 --> (グループへの招待を了承する)
    (ユーザーをグループに追加する) <-- システム
}
@enduml