@startuml
title ユーザー登録
left to right direction
actor ユーザー
actor システム
rectangle {
   ユーザー --> (メールアドレスとパスワードを入力し\nユーザー登録を行う)
   (入力されたメールアドレスに認証メールを送信する) <-- システム
   ユーザー --> (認証メールから認証を行い\nユーザー登録を完了する)
}
@enduml