@startuml ユーザープロフィール関連

title ユーザープロフィール関連

package "ユーザープロフィール集約(UserProfileAggregation)" {
    class "UserProfile\nユーザープロフィール" as UserProfile << (R,red) RootEntity >> {
        userId: UserId
        userName: UserName
        email: Email
        password: Password
        verificationStatus 認証済みかどうか: VerificationStatus
    }

    class UserId {
        - value: string
    }

    class UserName {
        - value: string
    }

    class Email {
        - value: string
    }

    class Password {
        - value: string
    }

    class "VerificationStatus\n認証済みの有無" as VerificationStatus {
        + value: Enum { verified(認証済み), unverified(未認証)}
    }

    note bottom of UserProfile
        「認証済みの有無」が「認証済み」の場合のみ、ログインが行える
    end note

    note bottom of UserId
        userIdはULIDやUUIDv7などの時系列ソート可能なIDを用いる
    end note

    note bottom of UserName
        ・ユーザー名は変更可能
        ・空白だけの文字列は受け付けない
        ・1文字以上20文字以下の文字列
        ・ユーザー名の初期値はメールアドレスのローカル部
        ・もしローカル部が20文字以上だった場合、20文字に切り取られる
    end note

    note bottom of VerificationStatus
        ・「認証済み」と「未認証」がある
        ・認証確認メールでの認証が済んだら「認証済み」になる 
    end note

    note bottom of Password
        パスワードはArgon2アルゴリズムを用いてハッシュ化する
    end note

    UserProfile *-down- UserId
    UserProfile *-down- UserName
    UserProfile *-down- Email
    UserProfile *-down- Password
    UserProfile *-down- VerificationStatus
}

package "認証確認(AuthenticationConfirmation)" {
    class "AuthenticationConfirmation\n認証確認" as AuthenticationConfirmation {
        temporarytoken: Temporarytoken
        userId: UserId
    }

    class "Temporarytoken\n一時的なトークン" as Temporarytoken {
        - value: string
    }

    note bottom of Temporarytoken
        ・ULIDをJWT(JSON Web Token)を使ってエンコードしたもの
        ・認証確認URLのクエリパラメータに追加される
        ・認証確認が済んだら削除する
        ・有効期限は24時間
    end note

    AuthenticationConfirmation *-down- Temporarytoken
    AuthenticationConfirmation -down-> UserProfile.UserId
}

@enduml